name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to deploy'
        required: false
        type: string
        default: 'dist-files'
    outputs:
      result:
        description: 'Result from the deployment step'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs['artifact-name'] }}
      - name: List contents
        run: ls
      - name: Deployment step
        run: echo "This is a reusable workflow deployment step."
      - name: Set result  
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
